name: Ludo-AppImage
on:
  schedule:
    - cron: "0 6 * * 0"
  workflow_dispatch:
  
jobs:
  build:
    name: 'setup os target'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
          
      - name: 'build appimage'
        run: |
          sudo apt update
          sudo apt install git wget curl file binutils patchelf findutils grep sed coreutils strace -y
          find -iname 'ludo-appimage*' | xargs -i -t -exec chmod a+x {} && find -iname 'ludo-appimage*' | xargs -i -t -exec {} +
          ./ludo-appimage.sh
          mkdir dist/
          mv Ludo-x86_64*.AppImage dist/
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'Ludo place'
          path: 'dist/*AppImage'

  release:
    needs: [build]
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Download Ludo artifact
        uses: actions/download-artifact@v4
        with:
          name: Ludo place

      - name: Delete Previous Release
        run: |
          gh release delete "${APP_VERSION}" --repo "${GITHUB_REPOSITORY}" --cleanup-tag -y || echo "No release to delete"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Continuous universal"
          tag_name: continuous-universal
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            *.AppImage*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
