name: Ludo AppImage

on:
  schedule:
    - cron: "0 0 */6 * *"
  push:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]
  workflow_dispatch:

jobs:
  build:
    name: setup os target
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Get Ludo version from GitHub
        run: |
          VERSION=$(curl -s https://api.github.com/repos/libretro/ludo/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create dist folder
        run: mkdir -p ./dist/

      - name: Make AppImage
        run: |
          set -ex
          pacman -Sy xorg-server-xvfb findutils file binutils patchelf grep sed coreutils strace wget curl glfw-x11 mesa openal fuse2 fuse3 --noconfirm
          chmod a+x ludo-appimage.sh
          ./ludo-appimage.sh
          find . -iname 'Ludo*.AppImage' -type f -exec mv {} ./dist/ \;
          echo "${APP_VERSION}" > dist/version

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: ./dist/*.AppImage

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: dist/version

  release:
    needs: [build]
